CREATE DATABASE DB_EMPLOYEE;

USE DB_EMPLOYEE;


CREATE TABLE TRA_EMPLOYEE
(
    ID         INT IDENTITY(1,1) PRIMARY KEY,
    FIRST_NAME NVARCHAR(100) NOT NULL,
    LAST_NAME  NVARCHAR(100) NOT NULL,
    EMAIL      NVARCHAR(200) NOT NULL,
    SALARY     DECIMAL(18, 2) NOT NULL,
    DEPARTMENT NVARCHAR(100) NOT NULL,
    HIREDATE   DATE           NOT NULL,
    IS_ACTIVE  BIT            NOT NULL DEFAULT 1
);
GO

INSERT INTO TRA_EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, SALARY, DEPARTMENT, HIREDATE, IS_ACTIVE) VALUES
('ANA', 'MARTINEZ', 'ANA.MARTINEZ@UNISUPERGT.COM', 1800.00, 'HR', '2018-03-10', 1),
('LUIS', 'RAMIREZ', 'LUIS.RAMIREZ@UNISUPERGT.COM', 2300.00, 'IT', '2021-07-01', 1),
('CARLA', 'SOTO', 'CARLA.SOTO@UNISUPERGT.COM', 2000.00, 'FINANCE', '2024-11-15', 1),
('PEDRO', 'GOMEZ', 'PEDRO.GOMEZ@UNISUPERGT.COM', 2500.00, 'OPERATIONS', '2016-01-20', 0),
('MARIA', 'LOPEZ', 'MARIA.LOPEZ@UNISUPERGT.COM', 1950.00, 'HR', '2023-05-08', 1),
('JORGE', 'CASTRO', 'JORGE.CASTRO@UNISUPERGT.COM', 2200.00, 'IT', '2019-09-30', 0),
('ELENA', 'RIOS', 'ELENA.RIOS@UNISUPERGT.COM', 2100.00, 'LEGAL', '2020-12-12', 1);


CREATE LOGIN [usr_employee]
WITH PASSWORD = 'Gt#N0mina2026$',
CHECK_POLICY = ON,
CHECK_EXPIRATION = ON;
GO

CREATE USER [usr_employee] FOR LOGIN [usr_employee];
GO

USE [DB_EMPLOYEE];
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[dbo].[TRA_EMPLOYEE] TO [usr_employee];
GO